id = "paraiso"
name = "Paraíso theme"
version = "1.0.2"
schema_version = 1
authors = ["Simon Holywell", "Jan T. Sott"]
description = "Paraíso theme adapted from the TextMate theme of the same name originally created by Jan T. Scott"
repository = "https://github.com/treffynnon/zed-Paraiso"
